name: .NET Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Lightning.NET
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x
            8.0.x
      - name: Install dependencies
        working-directory: ${{ runner.workspace }}/Lightning.NET
        run: dotnet restore
      - name: Build
        working-directory: ${{ runner.workspace }}/Lightning.NET
        run: dotnet build --no-restore
      - name: Test
        working-directory: ${{ runner.workspace }}/Lightning.NET
        run: dotnet test --no-build --no-restore --verbosity normal